name: common_utils
description: A collection of essential Flutter utilities, including theming helpers, a versatile form validator, and useful Dart extensions.
version: 1.0.0
repository: https://github.com/lorenacimpean/common_utils

environment:
  sdk: '>=3.9.2 <4.0.0'

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  diacritic: ^0.1.6
  collection: ^1.18.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
