name: common_utils
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  diacritic: ^0.1.6
  collection: ^1.18.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
